### ISSUE TITLE
About Operating System

### ISSUE THREAD

**Issue by Henry0132** [ChenDRAG/SfBC#1]
Hi,Chen,
I'm sorry to bother you.As a green hand about RL,I want to know what operating system which you are using.I use mamba(conda) which is in Windows,but I have found that many scripts do not work in Windows because its environment  is incompatible.
I really want to get started with RL,please help me!Thanks!

**Comment by ChenDRAG** [comment]
Hi, sorry for the late reply. Unfortunately, I run all my experiments on Linux, so I'm afraid I cannot foresee the problem you might encounter when deploying the algorithm on Windows with Conda. If you could give me more specific difficulties you have had, maybe I could help you out.

**Comment by Henry0132** [comment]
Thanks for your reply.Now,I have realized that the Reinforcement Learning environments may be better built on Ubuntu than Windows.Then,I will run your project in Ubuntu20.04.When I have a problem again, I will consult you.Thank you again!!!
