### ISSUE TITLE
Some errors when I ran a command about this project

### ISSUE THREAD

**Issue by Henry0132** [ChenDRAG/SfBC#2]
Hi,Chen!I'm sorry to bother you again.When I ran your project in Ubuntu20.04,I found there are many problems for me.
First,When I  use the command `python3 evaluation.py`,the terminal tell me that 
`Traceback (most recent call last):
  File "evaluation.py", line 79, in <module>
    eval(args)
  File "evaluation.py", line 54, in eval
    actor_loadpath = os.path.join("./models", args.env + str(args.seed) + args.actor_load_setting, "ckpt{}.pth".format(args.actor_load_epoch))
TypeError: can only concatenate str (not "NoneType") to str`
I search this error and the Google tell me that use `str` to convert to string type.And I change this code ` actor_loadpath = os.path.join("./models", args.env + str(args.seed) + args.actor_load_setting, "ckpt{}.pth".format(args.actor_load_epoch))` into ` actor_loadpath = os.path.join("./models", args.env + str(args.seed) + str(args.actor_load_setting), "ckpt{}.pth".format(args.actor_load_epoch))`.I wonder if this method is possible.
Next,When I make changes as above,the terminal tell me that 
`Traceback (most recent call last):
  File "evaluation.py", line 79, in <module>
    eval(args)
  File "evaluation.py", line 56, in eval
    ckpt = torch.load(actor_loadpath, map_location=args.device)
  File "/home/henry/mambaforge/envs/py3.7/lib/python3.7/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/henry/mambaforge/envs/py3.7/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/henry/mambaforge/envs/py3.7/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './models/halfcheetah-medium-v20None/ckpt600.pth'`
I don't know how to deal with these errors.Please help me!Thank you very much!!!

**Comment by ChenDRAG** [comment]
This error means that you haven't trained and saved the required behavior model and Q-nets in the correct directory. Please follow the instructions in Readme, and run
`python3 train_behavior.py`
and
`python3 train_critic.py`
first

**Comment by Henry0132** [comment]
sorry!I reply back late.thanks for your reply.I have solved this problem!
