### ISSUE TITLE
Loss curve

### ISSUE THREAD

**Issue by venom12138** [ChenDRAG/SfBC#3]
Hi, great work! I’m curious about the loss curve of the behavior model during diffusion process. Is it convenient for u to draw the curve? Or can u give me an approximate final loss?

**Comment by ChenDRAG** [comment]
Sorry for the late reply, I've been on vacation for the last week. I'm sorry to say it can be difficult to find the exact loss curve for each individual experiment of SfBC. However, I can provide some sampled diffusion-BC loss curves from my recent experiments. I hope they can help you.
![image](https://github.com/ChenDRAG/SfBC/assets/40993476/ffdbbf54-5389-4821-a8e8-5b54090357cb)

**Comment by venom12138** [comment]
Thanks!
