### ISSUE TITLE
Questions about parallel testing and random seed setting

### ISSUE THREAD

**Issue by return-sleep** [ChenDRAG/SfBC#4]
Thank you very much for your interesting work. I have some doubts about evaluation described in Appendix B.
1. May I ask if you trained the model with a random seed and then used different random seeds in the evaluation phase? The mean and variance of the results were calculated based on the scores of M(episodes)* N(test seeds) . train once and test multiple times?
2.  how do you choose the final model to report the result, the lateset ckpt or the average of latest 10 ckpts?
3. What part of the code you have generously provided is about the parallel evaluation scheme, which greatly speed up the evalution phase?

**Comment by ChenDRAG** [comment]
Sorry for the late reply. I've been busy with a deadline recently.
1. I recall that we trained 5 independent models with different train seeds, each model is evaluated under 20 or 10 seeds with different test seeds.  The performance is averaged under these 5*20 episodes. The std is the std across 5 independent runs.  
2. The last performance at the end of training.
3. https://github.com/ChenDRAG/SfBC/blob/d384e9f0f272f3760ba56db2a235383fb8faef45/utils.py#L51C1-L51C12.  It is simply a trick to efficiently utilize the parallel acceleration features of GPUs, though.
